### ISSUE TITLE
Tests fail on all platform except MacOSX

### ISSUE THREAD

**Issue by eserte** [oetiker/business-payment-swissesr#1]
See http://matrix.cpantesters.org/?dist=Business-Payment-SwissESR%200.11.1 for a fail/pass overview.

**Comment by eserte** [comment]
Same problem with 0.12.0: http://matrix.cpantesters.org/?dist=Business-Payment-SwissESR%200.12.0

**Comment by oetiker** [comment]
the problem is that the thing requires a 'full' texlive installation ... it seems that this is present on the testmac while the other testsystems do not have this available.
